<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Inertia Configuration
    |--------------------------------------------------------------------------
    |
    | Configure how Inertia renders the server-side application.
    |
    */

    /**
     * The root view template that Inertia will use when rendering the
     * initial HTML response from the server.
     */
    'root_view' => 'app',

    /**
     * Tells Inertia where to look for views. By default, this is your
     * resources/views directory.
     */
    'views_path' => resource_path('views'),

    /**
     * Tells Inertia to automatically serve the assets generated by Vite when
     * you're in development mode, without requiring you to run "npm run dev".
     *
     * Note: You may wish to disable this if you're using another Vite
     * configuration tool like Laravel Vite Plugin.
     */
    'ssr' => false,

    /**
     * Tells Inertia the URL to the SSR server if using server-side rendering.
     */
    'ssr_url' => env('INERTIA_SSR_URL', 'http://127.0.0.1:13714'),

    /**
     * Tells Inertia whether to bundle the SSR manifest with your build.
     * A lot of hosting platforms don't allow you to execute Node.js after
     * your build is complete, so this is helpful for SSR builds where you
     * have a separate Node.js service.
     */
    'ssr_bundle' => false,
];
