import headphones from "@/assets/p-headphones.jpg";
import watch from "@/assets/p-watch.jpg";
import knit from "@/assets/p-knit.jpg";
import sneaker from "@/assets/p-sneaker.jpg";
import bag from "@/assets/p-bag.jpg";
import lamp from "@/assets/p-lamp.jpg";
import scent from "@/assets/p-scent.jpg";
import sunglasses from "@/assets/p-sunglasses.jpg";

import catFashion from "@/assets/cat-fashion.jpg";
import catElectronics from "@/assets/cat-electronics.jpg";
import catAccessories from "@/assets/cat-accessories.jpg";
import catHome from "@/assets/cat-home.jpg";
import editorialImg from "@/assets/editorial.jpg";
import heroImg from "@/assets/hero.jpg";

export const categories = [
  { id: "all", name: "All Products", count: 12, image: heroImg, description: "Explore the full Atelier collection of modern essentials." },
  { id: "fashion", name: "Fashion", count: 248, image: catFashion, description: "Minimalist tailoring and premium cashmere knitwear." },
  { id: "electronics", name: "Electronics", count: 132, image: catElectronics, description: "Acoustic precision and sleek contemporary industrial design." },
  { id: "accessories", name: "Accessories", count: 96, image: catAccessories, description: "Handcrafted leather goods and precision timepieces." },
  { id: "lifestyle", name: "Lifestyle", count: 184, image: catHome, description: "Artisanal scents, ambient lighting, and objects for the home." },
];

export const products = [
  {
    id: 1,
    slug: "atelier-studio-headphones",
    name: "Atelier Studio Headphones",
    category: "Electronics",
    price: 149,
    compareAt: 199,
    rating: 4.9,
    reviews: 412,
    badge: "Sale",
    image: headphones,
    hover: lamp,
    alt: "Matte black over-ear wireless headphones",
    tagline: "Ultra-low distortion studio sound with hybrid active noise cancellation.",
    description:
      "Engineered for acoustic purists, the Atelier Studio Headphones combine bespoke 40mm beryllium drivers with advanced adaptive hybrid noise cancellation. Crafted with lightweight aircraft-grade aluminum and ultra-soft protein leather ear cushions, they deliver up to 45 hours of high-resolution playback on a single charge.",
    highlights: [
      "Custom 40mm Beryllium acoustic drivers",
      "Adaptive Hybrid Active Noise Cancellation (ANC)",
      "45-hour continuous battery life with quick charge",
      "Multipoint Bluetooth 5.3 with lossless aptX Adaptive",
      "CNC-machined aluminum chassis and memory foam ear pads",
    ],
    specs: [
      { label: "Driver Size", value: "40mm Beryllium Dynamic" },
      { label: "Frequency Response", value: "10Hz – 40,000Hz" },
      { label: "Battery Life", value: "45 Hours (ANC On)" },
      { label: "Connectivity", value: "Bluetooth 5.3 / 3.5mm Jack / USB-C Audio" },
      { label: "Weight", value: "245 grams" },
      { label: "Warranty", value: "2-Year Comprehensive Warranty" },
    ],
    colors: [
      { name: "Matte Obsidian", hex: "#1c1c1e", image: headphones },
      { name: "Raw Aluminum", hex: "#d1d5db", image: watch },
      { name: "Nordic Cream", hex: "#ede8df", image: knit },
    ],
    sizes: ["One Size"],
    inStock: true,
    stockCount: 14,
    sku: "ATL-EL-8942",
    images: [headphones, lamp, editorialImg, catElectronics],
    ratingBreakdown: { 5: 360, 4: 42, 3: 8, 2: 2, 1: 0 },
    reviewsList: [
      {
        id: "r1",
        author: "Marcus Vance",
        rating: 5,
        date: "2 days ago",
        verified: true,
        title: "Best studio sound profile in this price tier",
        content: "The tonal balance is pristine. Bass is punchy without muddying the vocal mids, and highs are silky smooth. Beautiful design as well.",
        helpful: 34,
      },
      {
        id: "r2",
        author: "Elena Rostova",
        rating: 5,
        date: "1 week ago",
        verified: true,
        title: "Incredible comfort for 8+ hour workdays",
        content: "I wear these all day during programming and zoom calls. The ear cushions are buttery soft and the microphone clarity is top notch.",
        helpful: 19,
      },
      {
        id: "r3",
        author: "David K.",
        rating: 4,
        date: "3 weeks ago",
        verified: true,
        title: "Fantastic build quality, premium case",
        content: "Love the physical tactile dial for volume control instead of finicky touch controls. Comes with a gorgeous magnetic carry case.",
        helpful: 8,
      },
    ],
    faqs: [
      {
        q: "Are these headphones water and sweat resistant?",
        a: "They are rated IPX4 water and splash resistant, making them suitable for light workouts and rainy commutes.",
      },
      {
        q: "Can I connect to two devices simultaneously?",
        a: "Yes, multipoint Bluetooth 5.3 enables seamless auto-switching between your laptop and smartphone.",
      },
      {
        q: "What is included in the package?",
        a: "Includes the Studio Headphones, magnetic hard-shell travel case, 3.5mm braided cable, USB-C fast charging cable, and flight adapter.",
      },
    ],
  },
  {
    id: 2,
    slug: "meridian-steel-watch",
    name: "Meridian Steel Watch",
    category: "Accessories",
    price: 320,
    rating: 4.8,
    reviews: 208,
    badge: "New",
    image: watch,
    hover: sunglasses,
    alt: "Minimal steel wristwatch with white dial",
    tagline: "Swiss-engineered precision movement encased in 316L surgical-grade steel.",
    description:
      "A tribute to classic Scandinavian Bauhaus horology. The Meridian features an ultra-slim 7.8mm case profile, scratch-resistant sapphire crystal with anti-reflective coating, and a genuine quick-release Italian calfskin band.",
    highlights: [
      "Swiss Ronda 715 quartz movement",
      "Sapphire crystal with triple anti-reflective coating",
      "316L surgical stainless steel case (39mm diameter)",
      "5 ATM / 50 meters water resistance",
      "Quick-release vegetable-tanned Italian leather strap",
    ],
    specs: [
      { label: "Case Diameter", value: "39mm" },
      { label: "Case Thickness", value: "7.8mm" },
      { label: "Movement", value: "Swiss Ronda Quartz 715" },
      { label: "Glass", value: "Domed Sapphire Crystal" },
      { label: "Strap Width", value: "20mm Interchangeable" },
      { label: "Water Resistance", value: "5 ATM (50m)" },
    ],
    colors: [
      { name: "Silver & Obsidian", hex: "#c0c0c0", image: watch },
      { name: "Rose Gold & Tan", hex: "#b76e79", image: bag },
      { name: "Midnight Black", hex: "#18181b", image: sunglasses },
    ],
    sizes: ["39mm", "42mm"],
    inStock: true,
    stockCount: 8,
    sku: "ATL-AC-3301",
    images: [watch, sunglasses, catAccessories, catFashion],
    ratingBreakdown: { 5: 178, 4: 24, 3: 4, 2: 2, 1: 0 },
    reviewsList: [
      {
        id: "rw1",
        author: "Julian Thorne",
        rating: 5,
        date: "5 days ago",
        verified: true,
        title: "Clean lines and understated luxury",
        content: "Understated elegance. People comment on it constantly. The dial has a subtle sunburst texture that catches natural light beautifully.",
        helpful: 28,
      },
      {
        id: "rw2",
        author: "Claire Sterling",
        rating: 5,
        date: "2 weeks ago",
        verified: true,
        title: "The 39mm size fits perfectly",
        content: "Slim enough to slide effortlessly under dress cuffs. The leather band softens up nicely within two days of wear.",
        helpful: 12,
      },
    ],
    faqs: [
      {
        q: "Can I swap the strap with other standard straps?",
        a: "Yes, the Meridian uses standard 20mm quick-release spring bars so you can change straps in 10 seconds without tools.",
      },
      {
        q: "What is the expected battery life?",
        a: "The Swiss battery delivers approximately 4.5 years of continuous runtime.",
      },
    ],
  },
  {
    id: 3,
    slug: "heavy-rib-cashmere-knit",
    name: "Heavy Rib Cashmere Knit",
    category: "Fashion",
    price: 189,
    compareAt: 240,
    rating: 4.9,
    reviews: 316,
    badge: "Sale",
    image: knit,
    hover: bag,
    alt: "Folded cream cashmere ribbed sweater",
    tagline: "100% Grade-A Mongolian cashmere spun into a substantial 7-gauge fisherman rib.",
    description:
      "Unparalleled softness meets everyday durability. Spun from sustainably sourced long-staple Mongolian cashmere, this fisherman rib sweater is pill-resistant, breathable, and provides natural thermo-regulation across all seasons.",
    highlights: [
      "100% certified organic Grade-A Mongolian cashmere",
      "Heavyweight 7-gauge 4-ply fisherman rib knit",
      "Reinforced collar, cuffs, and ribbed hem that holds shape",
      "Naturally thermo-regulating and moisture-wicking",
      "Ethically milled and finished without harsh chemical dyes",
    ],
    specs: [
      { label: "Material", value: "100% Grade-A Cashmere" },
      { label: "Gauge", value: "7-Gauge Heavy Rib" },
      { label: "Fit", value: "Relaxed tailored silhouette" },
      { label: "Care", value: "Hand wash cold or dry clean only" },
      { label: "Origin", value: "Spun in Biella, Italy" },
    ],
    colors: [
      { name: "Oatmeal Cream", hex: "#eae4d9", image: knit },
      { name: "Charcoal Heather", hex: "#374151", image: headphones },
      { name: "Forest Sage", hex: "#4b5563", image: catHome },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 19,
    sku: "ATL-FA-1094",
    images: [knit, bag, catFashion, editorialImg],
    ratingBreakdown: { 5: 290, 4: 21, 3: 4, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rk1",
        author: "Sophie Laurent",
        rating: 5,
        date: "3 days ago",
        verified: true,
        title: "The softest knit I have ever touched",
        content: "The weight is extraordinary — thick and cozy without feeling stifling. The oatmeal tone pairs with everything.",
        helpful: 41,
      },
      {
        id: "rk2",
        author: "Liam Chen",
        rating: 5,
        date: "2 weeks ago",
        verified: true,
        title: "True to size and doesn't stretch out",
        content: "I'm 6'1 wearing size Large. The sleeve length and drape are flawless. Zero pilling after 10+ wears.",
        helpful: 16,
      },
    ],
    faqs: [
      {
        q: "How should I wash and care for this knit?",
        a: "We recommend hand washing in cool water with gentle wool detergent, then laying flat on a towel to dry. A cashmere comb is included.",
      },
      {
        q: "Does this run true to size?",
        a: "Yes, it has an intentionally modern relaxed fit. If you prefer a closer tailored look, consider sizing down one size.",
      },
    ],
  },
  {
    id: 4,
    slug: "court-leather-sneakers",
    name: "Court Leather Sneakers",
    category: "Fashion",
    price: 165,
    rating: 4.7,
    reviews: 189,
    image: sneaker,
    hover: knit,
    alt: "White low-top leather sneakers",
    tagline: "Handcrafted in Portugal with supple full-grain Italian Nappa leather.",
    description:
      "The quintessential minimalist sneaker. Built on a vulcanized Margom-style rubber cupsole with memory foam insoles, the Court sneaker provides all-day arch support with effortless Scandinavian minimalism.",
    highlights: [
      "Full-grain buttery Italian Nappa leather upper",
      "Waxed cotton tonal laces with nickel eyelets",
      "Cushioned OrthoLite® ergonomic memory foam footbed",
      "Stitched vulcanized natural rubber cupsole",
      "Zero break-in period with ultra-plush leather lining",
    ],
    specs: [
      { label: "Upper", value: "Full-Grain Italian Calfskin" },
      { label: "Lining", value: "Vegetable-Tanned Calf Leather" },
      { label: "Sole", value: "Reinforced Rubber Cupsole" },
      { label: "Insole", value: "Removable Memory Foam Footbed" },
      { label: "Origin", value: "Porto, Portugal" },
    ],
    colors: [
      { name: "Chalk White", hex: "#fafafa", image: sneaker },
      { name: "Monochrome Black", hex: "#18181b", image: headphones },
      { name: "Sand Suede", hex: "#d7c4b7", image: bag },
    ],
    sizes: ["EU 39", "EU 40", "EU 41", "EU 42", "EU 43", "EU 44", "EU 45"],
    inStock: true,
    stockCount: 11,
    sku: "ATL-FA-4420",
    images: [sneaker, knit, catFashion, heroImg],
    ratingBreakdown: { 5: 145, 4: 36, 3: 6, 2: 2, 1: 0 },
    reviewsList: [
      {
        id: "rs1",
        author: "Oliver Brooks",
        rating: 5,
        date: "4 days ago",
        verified: true,
        title: "Cleanest white sneaker on the market",
        content: "Better leather quality than designer pairs costing double. Walked 15,000 steps on day one without any blisters.",
        helpful: 22,
      },
    ],
    faqs: [
      {
        q: "Are the insoles removable for custom orthotics?",
        a: "Yes, the padded leather-lined insoles are fully removable.",
      },
      {
        q: "How do I maintain the bright white leather?",
        a: "Wipe clean with a damp cloth and apply neutral leather conditioner once a month.",
      },
    ],
  },
  {
    id: 5,
    slug: "everyday-leather-tote",
    name: "Everyday Leather Tote",
    category: "Accessories",
    price: 240,
    rating: 4.8,
    reviews: 143,
    badge: "New",
    image: bag,
    hover: watch,
    alt: "Structured tan leather tote bag",
    tagline: "Full-grain Tuscan bridle leather built to hold your laptop and daily essentials.",
    description:
      "A masterclass in functional elegance. Features a padded 16-inch laptop compartment, dedicated water bottle slot, magnetized key leash, and reinforced saddle-stitched shoulder handles engineered to carry up to 25 lbs effortlessly.",
    highlights: [
      "Hand-finished Tuscan vegetable-tanned leather",
      "Dedicated padded compartment for laptops up to 16\"",
      "Dual interior slip pockets & secure zippered valuables pocket",
      "Reinforced base with protective brass feet",
      "Magnetic top bridge closure for easy one-hand access",
    ],
    specs: [
      { label: "Dimensions", value: "16.5\" W × 13.5\" H × 6.0\" D" },
      { label: "Handle Drop", value: "10.5 inches (Over-the-shoulder)" },
      { label: "Weight", value: "1.8 lbs" },
      { label: "Capacity", value: "18 Liters" },
      { label: "Hardware", value: "Brushed Antique Brass" },
    ],
    colors: [
      { name: "Cognac Tan", hex: "#b45309", image: bag },
      { name: "Espresso Brown", hex: "#3b1e08", image: catAccessories },
      { name: "Onyx Black", hex: "#0f172a", image: headphones },
    ],
    sizes: ["Standard (18L)"],
    inStock: true,
    stockCount: 6,
    sku: "ATL-AC-7782",
    images: [bag, watch, catAccessories, editorialImg],
    ratingBreakdown: { 5: 120, 4: 19, 3: 3, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rb1",
        author: "Hannah Wright",
        rating: 5,
        date: "1 week ago",
        verified: true,
        title: "The ultimate work and travel bag",
        content: "Holds my MacBook Pro, planner, charger pouch, and water bottle with room to spare. The leather patina gets better each week.",
        helpful: 18,
      },
    ],
    faqs: [
      {
        q: "Will a 16-inch MacBook Pro fit comfortably?",
        a: "Yes, the padded sleeve is specifically designed to accommodate laptops up to 16 inches with a protective snap closure.",
      },
    ],
  },
  {
    id: 6,
    slug: "arc-desk-lamp",
    name: "Arc Desk Lamp",
    category: "Lifestyle",
    price: 128,
    compareAt: 160,
    rating: 4.6,
    reviews: 97,
    badge: "Sale",
    image: lamp,
    hover: scent,
    alt: "Matte black minimalist desk lamp",
    tagline: "Architectural LED illumination with 3 warm ambient color temperatures.",
    description:
      "Crafted from cast zinc alloy and powder-coated steel, the Arc Desk Lamp provides flicker-free diffused lighting for focused work and evening reading. Includes step-less capacitive touch dimming and an integrated 15W Qi wireless phone charger in the base.",
    highlights: [
      "High-CRI 97+ natural spectrum LED (No eye strain)",
      "Capacitive touch dimmer with memory brightness recall",
      "Integrated 15W Qi fast wireless charging base",
      "3-axis counterbalanced articulation for precise angles",
      "Energy efficient 50,000-hour LED lifespan",
    ],
    specs: [
      { label: "Height", value: "18.5 inches (Adjustable)" },
      { label: "Base Diameter", value: "6.7 inches" },
      { label: "Lumens", value: "850 Lumens Max" },
      { label: "Color Temp", value: "2700K – 4500K Adjustable" },
      { label: "Power", value: "USB-C Braided Cable & 20W Wall Adapter" },
    ],
    colors: [
      { name: "Matte Black", hex: "#18181b", image: lamp },
      { name: "Brushed Brass", hex: "#d97706", image: watch },
      { name: "Pure Sand", hex: "#e5e7eb", image: scent },
    ],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 22,
    sku: "ATL-LS-9021",
    images: [lamp, scent, catHome, catElectronics],
    ratingBreakdown: { 5: 75, 4: 16, 3: 4, 2: 2, 1: 0 },
    reviewsList: [
      {
        id: "rl1",
        author: "Devin Ross",
        rating: 5,
        date: "2 weeks ago",
        verified: true,
        title: "Transforms my whole workspace vibe",
        content: "The warm 2700K setting creates such a calming atmosphere for late-night editing. Wireless charging pad on the base is super convenient.",
        helpful: 15,
      },
    ],
    faqs: [
      {
        q: "Does the base get warm when wireless charging?",
        a: "No, it features built-in thermal heatsink venting to ensure safe, cool Qi fast charging.",
      },
    ],
  },
  {
    id: 7,
    slug: "ash-and-cedar-diffuser",
    name: "Ash & Cedar Diffuser",
    category: "Lifestyle",
    price: 68,
    rating: 4.9,
    reviews: 275,
    image: scent,
    hover: lamp,
    alt: "Frosted glass reed diffuser and ceramic vessel",
    tagline: "Slow-diffusing organic botanical oils with notes of Japanese Hinoki and smoked cedar.",
    description:
      "Formulated by master perfumers in Grasse, France. Features pure essential oils suspended in alcohol-free eco-solvent for a continuous 4-month aromatic aura. Encased in hand-blown smoked fluted glass with 8 natural black rattan reeds.",
    highlights: [
      "Top notes: Smoked Hinoki, Cardamom, Crisp Bergamot",
      "Heart notes: Atlas Cedarwood, White Birch, Patchouli",
      "Base notes: Amber Resin, Cashmere Musk, Vetiver",
      "Alcohol-free and phthalate-free clean formula",
      "Diffuses continuously for 120+ days",
    ],
    specs: [
      { label: "Volume", value: "200ml / 6.7 fl oz" },
      { label: "Longevity", value: "4 to 5 Months" },
      { label: "Reeds Included", value: "8 Natural Black Rattan Reeds" },
      { label: "Vessel", value: "Hand-Blown Smoked Glass" },
      { label: "Origin", value: "Grasse, France" },
    ],
    colors: [
      { name: "Smoked Glass", hex: "#4b5563", image: scent },
      { name: "Frosted Amber", hex: "#b45309", image: lamp },
    ],
    sizes: ["200ml / 6.7 oz", "500ml Refill"],
    inStock: true,
    stockCount: 35,
    sku: "ATL-LS-5510",
    images: [scent, lamp, catHome, knit],
    ratingBreakdown: { 5: 250, 4: 20, 3: 4, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rd1",
        author: "Maya Lin",
        rating: 5,
        date: "3 days ago",
        verified: true,
        title: "Smells like a 5-star Kyoto boutique hotel",
        content: "Not overpowering or synthetic at all. Guests constantly compliment the scent the moment they walk into our living room.",
        helpful: 39,
      },
    ],
    faqs: [
      {
        q: "How often should I flip the reeds?",
        a: "Flip the reeds once every 1–2 weeks to refresh the scent throw.",
      },
    ],
  },
  {
    id: 8,
    slug: "titan-amber-sunglasses",
    name: "Titan Amber Sunglasses",
    category: "Accessories",
    price: 145,
    rating: 4.7,
    reviews: 88,
    badge: "New",
    image: sunglasses,
    hover: watch,
    alt: "Thin titanium sunglasses with amber lenses",
    tagline: "Ultralight Japanese beta-titanium frames with polarized UV400 amber lenses.",
    description:
      "Weighing a featherlight 14 grams, the Titan frame combines aerospace-grade Japanese beta-titanium with hand-beveled amber polarized lenses. Provides 100% UVA/UVB protection and enhances contrast across both sunny days and golden hour commutes.",
    highlights: [
      "Ultra-lightweight Japanese Beta-Titanium wireframe",
      "Polarized Category 3 Amber lenses with anti-scratch coating",
      "100% UVA/UVB/UVC 400 protection",
      "Hypoallergenic titanium nose pads with silicone cushions",
      "Custom collapsible vegan leather protective case",
    ],
    specs: [
      { label: "Frame Width", value: "138mm" },
      { label: "Bridge Width", value: "19mm" },
      { label: "Temple Length", value: "145mm" },
      { label: "Weight", value: "14 grams" },
      { label: "Lens Category", value: "Cat 3 Polarized" },
    ],
    colors: [
      { name: "Titanium Gold", hex: "#eab308", image: sunglasses },
      { name: "Gunmetal Silver", hex: "#64748b", image: watch },
      { name: "Matte Black", hex: "#1e293b", image: headphones },
    ],
    sizes: ["One Size (Medium / Universal Fit)"],
    inStock: true,
    stockCount: 17,
    sku: "ATL-AC-6129",
    images: [sunglasses, watch, catAccessories, catFashion],
    ratingBreakdown: { 5: 68, 4: 16, 3: 3, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rsu1",
        author: "Kian Sterling",
        rating: 5,
        date: "1 week ago",
        verified: true,
        title: "So lightweight you forget you're wearing them",
        content: "Crystal clear optical clarity without any distortion. The amber tint makes everything look warm and vibrant.",
        helpful: 14,
      },
    ],
    faqs: [
      {
        q: "Can I fit prescription lenses into these frames?",
        a: "Yes, any certified optometrist can easily install custom prescription lenses into the Titan frame.",
      },
    ],
  },
  {
    id: 9,
    slug: "tailored-linen-overshirt",
    name: "Tailored Linen Overshirt",
    category: "Fashion",
    price: 135,
    compareAt: 170,
    rating: 4.8,
    reviews: 114,
    badge: "Sale",
    image: catFashion,
    hover: knit,
    alt: "Structured natural linen button-down overshirt",
    tagline: "100% French Normandy flax linen with horn buttons and double chest utility pockets.",
    description:
      "The ideal transitional layer. Woven from breathable French flax linen that has been garment-washed for immediate broken-in comfort. Features real mother-of-pearl buttons and clean felled seams for decades of wear.",
    highlights: [
      "100% certified Normandy flax linen",
      "Garment-dyed and enzyme washed for supreme softness",
      "Natural genuine corozo horn buttons",
      "Dual patch pockets and hidden interior passport slot",
      "Pre-shrunk for consistent fit wash after wash",
    ],
    specs: [
      { label: "Material", value: "100% French Linen" },
      { label: "Weight", value: "220 GSM Mid-weight" },
      { label: "Fit", value: "Tailored Boxy Silhouette" },
      { label: "Care", value: "Machine wash delicate cold, hang dry" },
      { label: "Origin", value: "Normandy, France" },
    ],
    colors: [
      { name: "Sand Flax", hex: "#e2d9cc", image: catFashion },
      { name: "Deep Navy", hex: "#1e3a8a", image: headphones },
      { name: "Olive Moss", hex: "#3f4f38", image: knit },
    ],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    stockCount: 15,
    sku: "ATL-FA-9912",
    images: [catFashion, knit, editorialImg, sneaker],
    ratingBreakdown: { 5: 98, 4: 12, 3: 3, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rt1",
        author: "Anthony Miller",
        rating: 5,
        date: "2 weeks ago",
        verified: true,
        title: "Perfection in craftsmanship and cut",
        content: "Drapes exceptionally well over a plain white tee or light knit. Breathable in heat and looks effortlessly chic.",
        helpful: 21,
      },
    ],
    faqs: [
      {
        q: "Will the linen shrink in the laundry?",
        a: "Our linen is pre-washed and pre-shrunk, so it retains its exact dimensions when washed according to care instructions.",
      },
    ],
  },
  {
    id: 10,
    slug: "hifi-wireless-charging-stand",
    name: "Hi-Fi Acoustic Soundbar",
    category: "Electronics",
    price: 280,
    rating: 4.9,
    reviews: 162,
    badge: "New",
    image: catElectronics,
    hover: headphones,
    alt: "Aluminum and wood acoustic desktop soundbar",
    tagline: "Stereo spatial audio with integrated dual passive subwoofers and walnut accents.",
    description:
      "Transform your workspace or television setup. Combining dual silk-dome tweeters, dual neodymium woofers, and real FSC-certified American walnut timber end caps, this acoustic bar delivers breathtakingly wide 3D soundstages.",
    highlights: [
      "True 2.1 channel spatial stereo architecture",
      "Real solid American Walnut timber housing",
      "Optical, HDMI eARC, Bluetooth 5.3, and AUX inputs",
      "Custom DSP EQ modes: Music, Film, Vocal, Studio",
      "Machined aluminum remote control included",
    ],
    specs: [
      { label: "Power Output", value: "120W Peak (60W RMS)" },
      { label: "Frequency Range", value: "35Hz – 22,000Hz" },
      { label: "Dimensions", value: "24\" W × 3.2\" H × 4.1\" D" },
      { label: "Inputs", value: "HDMI eARC, Optical, 3.5mm, BT 5.3" },
      { label: "Origin", value: "Designed in Denmark" },
    ],
    colors: [
      { name: "Walnut & Matte Slate", hex: "#78350f", image: catElectronics },
      { name: "Oak & Silver Mesh", hex: "#d1d5db", image: watch },
    ],
    sizes: ["24\" Standard", "36\" Pro Cinema"],
    inStock: true,
    stockCount: 7,
    sku: "ATL-EL-4409",
    images: [catElectronics, headphones, lamp, heroImg],
    ratingBreakdown: { 5: 148, 4: 11, 3: 2, 2: 1, 1: 0 },
    reviewsList: [
      {
        id: "rh1",
        author: "Gabriel Santos",
        rating: 5,
        date: "3 weeks ago",
        verified: true,
        title: "Room-filling cinema sound in a compact bar",
        content: "Hooked it up via HDMI eARC. Dialogue is razor sharp and the low end rumble makes movie nights incredible.",
        helpful: 29,
      },
    ],
    faqs: [
      {
        q: "Does it work seamlessly with Apple TV and smart TVs?",
        a: "Yes, HDMI eARC allows you to power it on/off and control sound directly with your standard TV remote.",
      },
    ],
  },
  {
    id: 11,
    slug: "sculptural-ceramic-vase-duo",
    name: "Sculptural Ceramic Vase Duo",
    category: "Lifestyle",
    price: 95,
    rating: 4.8,
    reviews: 73,
    image: catHome,
    hover: scent,
    alt: "Handcrafted unglazed matte stoneware vase set",
    tagline: "Hand-thrown porous stoneware with architectural brutalist geometries.",
    description:
      "A pair of organically shaped ceramic vessels handcrafted in small batches in Kyoto. Featuring a raw tactile textured exterior and a waterproof glazed interior, perfect for dried botanicals or fresh seasonal floral arrangements.",
    highlights: [
      "Hand-thrown high-fire stoneware clay",
      "Porous textured matte sand finish",
      "Water-sealed glazed interior for fresh flowers",
      "Set of 2 complementary architectural silhouettes",
      "Felt padded base to safeguard tabletop surfaces",
    ],
    specs: [
      { label: "Vase A Dimensions", value: "9.2\" H × 5.5\" W" },
      { label: "Vase B Dimensions", value: "6.8\" H × 6.2\" W" },
      { label: "Material", value: "100% Natural Stoneware Clay" },
      { label: "Finish", value: "Unglazed Sand Matte" },
      { label: "Origin", value: "Kyoto, Japan" },
    ],
    colors: [
      { name: "Raw Terracotta Sand", hex: "#d97706", image: catHome },
      { name: "Volcanic Slate", hex: "#334155", image: scent },
    ],
    sizes: ["Set of 2"],
    inStock: true,
    stockCount: 18,
    sku: "ATL-LS-1928",
    images: [catHome, scent, lamp, editorialImg],
    ratingBreakdown: { 5: 64, 4: 7, 3: 2, 2: 0, 1: 0 },
    reviewsList: [
      {
        id: "rv1",
        author: "Chloe Dubois",
        rating: 5,
        date: "1 month ago",
        verified: true,
        title: "Stunning sculptural centerpiece",
        content: "Looks like art pieces you'd see in an upscale design museum. The texture is gorgeous.",
        helpful: 17,
      },
    ],
    faqs: [
      {
        q: "Can these hold water for live cut flowers?",
        a: "Yes, both vases are glazed on the interior to be 100% watertight.",
      },
    ],
  },
  {
    id: 12,
    slug: "minimalist-leather-cardholder",
    name: "Minimalist Bifold Cardholder",
    category: "Accessories",
    price: 75,
    compareAt: 95,
    rating: 4.9,
    reviews: 154,
    badge: "Sale",
    image: catAccessories,
    hover: watch,
    alt: "Slim vegetable tanned leather pocket cardholder",
    tagline: "RFID-blocking slim bifold with 6 card slots and quick-draw center cash pocket.",
    description:
      "Engineered to eliminate pocket bulk. Hand-stitched with waxed polyester thread and featuring beveled and burnished edges, this slim wallet holds 8–10 cards and folded bills with absolute minimum footprint.",
    highlights: [
      "Ultra-compact 0.3-inch slim profile",
      "RFID blocking shield for contactless card protection",
      "6 exterior precision card slots + center cash slot",
      "Full-grain French Chevre goat leather",
      "Hand-burnished and beeswax-sealed edges",
    ],
    specs: [
      { label: "Dimensions", value: "4.1\" L × 2.9\" W × 0.3\" D" },
      { label: "Capacity", value: "8–10 Cards + Cash" },
      { label: "Weight", value: "32 grams" },
      { label: "Shielding", value: "13.56 MHz RFID Blocking" },
      { label: "Origin", value: "Leon, Mexico" },
    ],
    colors: [
      { name: "Caramel Tan", hex: "#b45309", image: catAccessories },
      { name: "Racing Green", hex: "#14532d", image: watch },
      { name: "Stealth Black", hex: "#0f172a", image: sunglasses },
    ],
    sizes: ["Slim"],
    inStock: true,
    stockCount: 29,
    sku: "ATL-AC-5590",
    images: [catAccessories, watch, bag, heroImg],
    ratingBreakdown: { 5: 140, 4: 12, 3: 2, 2: 0, 1: 0 },
    reviewsList: [
      {
        id: "rc1",
        author: "Patrick Reed",
        rating: 5,
        date: "2 weeks ago",
        verified: true,
        title: "The only wallet you'll ever need",
        content: "Slides seamlessly into front pockets without any outline. The leather feels soft yet extremely durable.",
        helpful: 25,
      },
    ],
    faqs: [
      {
        q: "Does it hold international currency bills?",
        a: "Yes, folded US Dollars, Euros, British Pounds, and Yen fit comfortably in the center pocket.",
      },
    ],
  },
];

export const filters = ["All", "Fashion", "Electronics", "Accessories", "Lifestyle"];

export const sortOptions = [
  { id: "featured", label: "Featured & Popular" },
  { id: "price-asc", label: "Price: Low to High" },
  { id: "price-desc", label: "Price: High to Low" },
  { id: "rating-desc", label: "Highest Rated" },
  { id: "reviews-desc", label: "Most Reviewed" },
  { id: "name-asc", label: "Name: A to Z" },
];

export const testimonials = [
  {
    quote:
      "The quality is incredible and the entire shopping experience feels premium — from the packaging to the follow-up.",
    name: "Amara Osei",
    role: "Verified Customer",
  },
  {
    quote:
      "I've replaced half my wardrobe with pieces from here. Everything arrives fast and looks better in person.",
    name: "Julian Reyes",
    role: "Verified Customer",
  },
  {
    quote:
      "Finally a store that curates instead of overwhelming. The returns process took me under two minutes.",
    name: "Sofia Lindqvist",
    role: "Verified Customer",
  },
];

export const socialImages = [
  { src: catFashion, alt: "Model in tailored black outfit walking in the city" },
  { src: knit, alt: "Folded cream cashmere knit" },
  { src: catHome, alt: "Ceramic vases on an oak shelf" },
  { src: sneaker, alt: "White leather sneakers in sunlight" },
  { src: catAccessories, alt: "Leather belt, watch and gold jewellery" },
  { src: scent, alt: "Reed diffuser in warm daylight" },
];

const CURRENCY_SYMBOLS = { USD: "$", EUR: "€", GBP: "£", JPY: "¥", SEK: "kr" };

export const getCurrencySymbol = (currency = globalThis.__STORE_CURRENCY__) => {
  const code = String(currency || "USD").split(" ")[0].toUpperCase();
  return CURRENCY_SYMBOLS[code] || code;
};

export const formatPrice = (value, decimals = 0) => `${getCurrencySymbol()}${Number(value).toFixed(decimals)}`;
